//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Calculation
    {
        public System.DateTime CurentDate { get; set; }
        public decimal HourFee { get; set; }
        public decimal ConsumablesCost { get; set; }
        public decimal EquipmentMaintanance { get; set; }
    }
}
