//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Call()
        {
            this.CallDetails = new HashSet<CallDetail>();
        }
    
        public System.Guid CallID { get; set; }
        public System.DateTime CallDate { get; set; }
        public System.Guid CustomerID { get; set; }
        public string DocNumber { get; set; }
        public int AffidavitNum { get; set; }
        public System.DateTime AffidavitDate { get; set; }
        public System.DateTime ContractDate { get; set; }
        public int CallStatus { get; set; }
        public string DocType { get; set; }
        public Nullable<decimal> Cost_Efficiency { get; set; }
        public System.DateTime SampleActDate { get; set; }
        public string CallName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallDetail> CallDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
