//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallStatus
    {
        public System.Guid CallStatusID { get; set; }
        public int CallStatus1 { get; set; }
        public string CallStatusName { get; set; }
    }
}
