//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSubtype()
        {
            this.Items = new HashSet<Item>();
        }
    
        public System.Guid ItemSubtypeID { get; set; }
        public string ItemSubtype1 { get; set; }
        public System.Guid ItemTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
