//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabEquipment
    {
        public System.Guid EquipmentID { get; set; }
        public System.Guid EquipmentTypeID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentTypeCode { get; set; }
        public string EquipmentFactoryID { get; set; }
        public string EquipmentInventoryID { get; set; }
        public short EquipmentMark { get; set; }
        public System.Guid EquipmentPlaceID { get; set; }
        public Nullable<System.DateTime> DateOfTest { get; set; }
        public Nullable<long> ExpiryDate { get; set; }
        public Nullable<System.DateTime> DateOfDisposal { get; set; }
        public Nullable<long> DispProtocolNumber { get; set; }
        public Nullable<System.Guid> EquipmentStatusID { get; set; }
        public Nullable<System.Guid> RespPersonID { get; set; }
        public string PeriodOfValidity { get; set; }
    
        public virtual EquipmentStatus EquipmentStatus { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Expert Expert { get; set; }
        public virtual LabRoom LabRoom { get; set; }
    }
}
