//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Experts = new HashSet<Expert>();
        }
    
        public System.Guid OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.Guid ItemID { get; set; }
        public Nullable<System.Guid> ExpertID { get; set; }
        public long OrderNumber { get; set; }
        public System.DateTime FinalDate { get; set; }
        public System.Guid CallID { get; set; }
    
        public virtual CallDetail CallDetail { get; set; }
        public virtual Expert Expert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expert> Experts { get; set; }
    }
}
