USE [master]
GO

/****** Object:  Database [GunSudex]    Script Date: 26/08/2018 21:32:07 ******/
CREATE DATABASE [GunSudex]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GunSudex', FILENAME = N'D:\Install\AdminLTE-ASP-NET-MVC-master\adminlte\App_Data\GunSudexNew.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GunSudex_log', FILENAME = N'D:\Install\AdminLTE-ASP-NET-MVC-master\adminlte\App_Data\GunSudexNew_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GunSudex] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GunSudex].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GunSudex] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GunSudex] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GunSudex] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GunSudex] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GunSudex] SET ARITHABORT OFF 
GO

ALTER DATABASE [GunSudex] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GunSudex] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GunSudex] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GunSudex] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GunSudex] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GunSudex] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GunSudex] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GunSudex] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GunSudex] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GunSudex] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GunSudex] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GunSudex] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GunSudex] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GunSudex] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GunSudex] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GunSudex] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GunSudex] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GunSudex] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GunSudex] SET  MULTI_USER 
GO

ALTER DATABASE [GunSudex] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GunSudex] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GunSudex] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GunSudex] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GunSudex] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GunSudex] SET  READ_WRITE 
GO

