USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

ALTER TABLE [dbo].[WeaponTypes] ADD  CONSTRAINT [WeaponTypeID_def]  DEFAULT (newsequentialid()) FOR [WeaponTypeID]
GO


USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

ALTER TABLE [dbo].[TestMethods] ADD  CONSTRAINT [MethodID_def]  DEFAULT (newsequentialid()) FOR [MethodID]
GO




USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

ALTER TABLE [dbo].[Representatives] ADD  CONSTRAINT [RepresentativeID_def]  DEFAULT (newsequentialid()) FOR [RepresentativeID]
GO


USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

ALTER TABLE [dbo].[Representatives] ADD  Position varchar (50) NULL
GO



USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

ALTER TABLE [dbo].[Roles] ADD  CONSTRAINT [RolesID_def]  DEFAULT (newsequentialid()) FOR [RolesID]
GO


USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO

--ALTER TABLE [dbo].[Roles] DROP COLUMN RoleID

ALTER TABLE [dbo].[Roles] ADD RoleID uniqueidentifier PRIMARY KEY DEFAULT (NEWID())
GO

ALTER TABLE [dbo].[Experts] 
ADD CONSTRAINT FK_Roles_Experts
FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
GO

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO Roles (RoleDescr) VALUES ('Менеджер')
GO

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO Roles (RoleDescr) VALUES ('Исполнитель')
GO


USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
SELECT *
FROM Roles

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO WeaponTypes (WeaponTypeDescr) VALUES ('Холодное и метательное оружие')
GO

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO WeaponTypes (WeaponTypeDescr) VALUES ('Патроны')
GO

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO WeaponTypes (WeaponTypeDescr) VALUES ('Пневматическое оружие')
GO

USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
INSERT INTO WeaponTypes (WeaponTypeDescr) VALUES ('Газовое и сигнальное оружие')
GO


USE [C:\R&D\PROJECTS\28_08_2018\ADMINLTE-ASP-NET-MVC-MASTER\ADMINLTE\APP_DATA\GUNSUDEX.MDF]
GO
SELECT *
FROM WeaponTypes

